<?php

namespace Tests\Feature;

use Database\Seeders\ProductIngredientSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class PlaceOrderTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        (new ProductIngredientSeeder())->run();
    }

    /**
     * A basic feature test example.
     */
    public function testPlaceOneOrder(): void
    {

        $response = $this->postJson(
            uri: route('placeOrder'),
            data: [
                'products' => [
                    [
                        'product_id' => 1,
                        'quantity' => 1,
                    ],
                ],
            ],
            headers: [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json',
            ],
        );
        $response->assertStatus(200);
        $this->assertDatabaseCount('orders', 1);
    }
}
